books/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from bookstore import views
from django.views.generic import ListView
from bookstore.models import Book
from django.conf.urls import *
from django.contrib.auth.views import login, logout

urlpatterns = patterns('',
    url(r'^list/$', views.BookList.as_view(), name='books_list'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^book/(?P<book_id>\d+)$', views.book, name='book_detail'),
    url(r'^genre/(?P<genre>.*)$', views.bookstore_list, name='bookstore_list'),
    url(r'^author/(?P<author>.*)$', views.bookstore_author, name='bookstore_list'),
    url(r'^listall/$', ListView.as_view(model=Book), name = 'listall'),
    url(r'^list/(?P<genre>.*)$', views.BookList.as_view(), name='bookstore_list'),
    url(r'^detail/(?P<book_id>\d+)$', views.book, name='detail'), 
    #url(r'^add/$', views.BookCreate.as_view(), name='book_add'),
    url(r'^book/(?P<pk>\d+)/edit/$', views.BookUpdate.as_view(),  name='book_update'),
    url(r'^book/(?P<pk>\d+)/delete/$', views.BookDelete.as_view(),  name='book_delete'),
    url(r'^add/$', views.MyView.as_view(), name="book_add"),

    url(r'^book/(?P<pk>\d+)$', views.BookDetail.as_view(),  name='detail'),
    url(r'^accounts/', include('accounts.urls')),
    
)





    

bookstore/models.py
from django.db import models
from django.core.urlresolvers import reverse
from accounts.models import UserProfile

# Create your models here.
class Book(models.Model):
    user = models.ForeignKey(UserProfile, blank=True, null=True)
    title = models.CharField(max_length=255)
    synopsis = models.TextField(blank=True) #not a required field
    due = models.DateTimeField(null=True, blank=True) #due datetime is optional
    created = models.DateTimeField(auto_now_add=True, auto_now=False, null=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, null=True)
    done = models.BooleanField(default=False)
    color = models.CharField(max_length=50, default="yellow")
    fontcolor = models.CharField(max_length=50, default="black")
    #folder is optional
    genre = models.ForeignKey('Genre', related_name= "bookstore", null=True, blank=True)
    #tag is optional
    author = models.ManyToManyField('Author', related_name='bookstore', null=True, blank=True)
    
    def __str__(self):
        return self.title
        
    def get_absolute_url(self):
        return reverse("detail", kwargs={"pk":self.pk})

    
        

class Genre(models.Model):
    title = models.CharField(max_length=255)
    color = models.CharField(max_length=50, default="blue")
    fontcolor = models.CharField(max_length=50, default="white")
    
    def __str__(self):
        return self.title
        
class Author(models.Model):
    title = models.CharField(max_length=255)
    color = models.CharField(max_length=50, default="red")
    fontcolor = models.CharField(max_length=50, default="black")
    
    def __str__(self):
        return self.title

    
    def __unicode__(self):
        return self.title

bookstore/forms.py
from bookstore.models import Book
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field
from .models import Book, Genre, Author
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Hidden, Button, HTML, Div, Field, Row, Fieldset


class BookForm(forms.ModelForm):
    class Meta: 
        model = Book
        fields = '__all__'
        
    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('Save', 'Save', css_class='btn-primary'))

    def __init__(self, *args, **kwargs):
        super(BookForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_id = "bookform"
        
        #Create a new folder select list, with added css and style codes
        genre = Div('genre', css_class="col-xs-12", style="padding:0px;") 
        self.helper.layout.pop(6) #remove the original folder select list 
        #Insert new folder select list with a "Create New Folder" button as a Fieldset
        self.helper.layout.insert(6,Fieldset("Select genre",genre, Button("creategenremodal", value="Add New Genre", css_class="btn btn-primary btn-sm col-xs-12 ", data_toggle="modal", data_target="#myModal")))
        
        #Create a new tag multi-select list, with added css and style codes
        author = Div('author',css_class = "col-xs-12", style="padding:0px;") 
        oldtagselect = self.helper.layout.pop(7) #remove the original tag multi-select list
        #Insert new tag multi-select list with a "Create New Tag" button as a Fieldset
        self.helper.layout.insert(7, Fieldset("Select Author",author, Button("createauthormodal", value="Add New Author", css_class="btn btn-primary btn-sm col-xs-12", data_toggle="modal", data_target="#myModal2")))
        
        #Create a "Create New Note" button 
        self.helper.layout.append(Submit('btn_addbook', 'Add Book', css_class='addbook', style="margin-top:15px;"))
        #Add a hidden field 'btn_createnote' so that it will be submitted together in the form to allow server side to 'know'
        #that this button has been clicked
        self.helper.layout.append(Hidden(name='btn_addbook', value="btn_addbook"))
        
        
        
    def full_clean(self):
        #http://stackoverflow.com/questions/4340287/override-data-validation-on-one-django-form-element
        super(BookForm, self).full_clean()
        if 'tag' in self._errors:
            self.cleaned_data['tag'] = []
            print("remove tag errors")
            del self._errors['tag']
            
            
            
class GenreForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = '__all__'
        
    def __init__(self, *args, **kwargs):
        super(GenreForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_id = "genreform"
        self.helper.layout.append(Hidden(name='btn_creategenre', value="btn_creategenre"))
        self.helper.layout.append(Submit('btn_creategenre', 'Add Genre', css_class='creategenre', data_dismiss="modal"))
  

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = '__all__'

        
    def __init__(self, *args, **kwargs):
        super(AuthorForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_id = "authorform"
        self.helper.layout.append(Hidden(name='btn_createauthor', value="btn_createauthor"))
        self.helper.layout.append(Submit('btn_createauthor', 'Add Author', css_class='createauthor', data_dismiss="modal"))

bookstore/views.py
from django.shortcuts import render
from django.http import HttpResponse
#from .models import Book
from django.core.urlresolvers import reverse
import re
from django.db.models import Q
from django.views.generic import ListView
from .models import Book
from django.views.generic.edit import CreateView
from bookstore.forms import BookForm
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView
from django.views.generic import DetailView
from django.core.urlresolvers import reverse_lazy
from .models import Book, Genre, Author
from .forms import BookForm, GenreForm, AuthorForm
from django.views.generic import DetailView, ListView, TemplateView

from django.core.serializers.json import DjangoJSONEncoder
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from accounts.models import UserProfile

class MyView(TemplateView):
    #setup the various forms in this view
    genre_form_class = GenreForm
    author_form_class = AuthorForm
    book_form_class = BookForm
    template_name = "bookstore/book_hybrid.html"
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(MyView, self).dispatch(*args, **kwargs)


    #called when loading the page for a new entry
    def get(self, request, *args, **kwargs):
        #setup all the forms by intialising the various form names with the corresponding form class
        kwargs.setdefault("addgenre_form", self.genre_form_class())
        kwargs.setdefault("addauthor_form", self.author_form_class())
        kwargs.setdefault("addbook_form", self.book_form_class())
         #Added curruser so that profile picture of curruser can be rendered.
        #kwargs.setdefault('curruser', UserProfile.objects.get(user=self.request.user))

        return super(MyView, self).get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        form_args = {
            'data': self.request.POST,
        }
        
        #if btn_createfolder hidden field is a value in POST form
        if "btn_creategenre" in request.POST['form']: 
            form = self.folder_form_class(**form_args)
            #check if form is not value, reload the form with the POST values
            if not form.is_valid():
                #Construct the failed status (0) and the errors as message to be displayed in the template
                response_dict = {}
                response_dict['status'] = 0
                response_dict['message'] = form.errors.as_ul()
                return HttpResponse(json.dumps(response_dict, cls=DjangoJSONEncoder))
            else:
                #form is valid, save the form, and return all folders as data to update the folder select list
                form.save()
                data = Genre.objects.all()
                response_dict = {'status': 1}
                response_dict['message'] = list(data.values('id','title'))
                return HttpResponse(json.dumps(response_dict, cls=DjangoJSONEncoder))
        #if btn_createtag hidden field is a value in POST form
        elif "btn_createauthor" in request.POST['form']: 
            form = self.tag_form_class(**form_args)
            if not form.is_valid():
                #Construct the failed status (0) and the errors as message to be displayed in the template
                response_dict = {}
                response_dict['status'] = 0
                response_dict['message'] = form.errors.as_ul()
                return HttpResponse(json.dumps(response_dict, cls=DjangoJSONEncoder))
                #return self.get(request, createtag_form=form)
            else:
                #form is valid, save the form, and return all folders as data to update the tag multi-select list
                form.save() #save the new object
                data = Author.objects.all() # retrieve all records
                response_dict = {'status': 1}
                response_dict['message'] = list(data.values('id','title'))
                return HttpResponse(json.dumps(response_dict, cls=DjangoJSONEncoder)) #return to ajax as success with all the new records.
        #if btn_createnote hidden field is a value in POST form
        elif "btn_addbook" in request.POST['form']:
            form = self.note_form_class(**form_args)
            if not form.is_valid():
                #Construct the failed status (0) and the errors as message to be displayed in the template
                response_dict = {}
                response_dict['status'] = 0
                response_dict['message'] = form.errors.as_ul()
                return HttpResponse(json.dumps(response_dict, cls=DjangoJSONEncoder))
                #return self.get(request, createnote_form=form, errors=response_dict) 
            else:
                #form is valid, save the form, and return all folders as data to update the tag multi-select list
                try:
                    #Find out which user is logged in and get the correct UserProfile record.
                    curruser = UserProfile.objects.get(user=self.request.user)
                    obj = form.save(commit=False)
                    obj.user = curruser #Save the note note under that user
                    obj.save() #save the new object
                    
                except Exception, e:
                    print("errors" + str(e))
                response = {'status': 1, 'message':'ok'}
                return HttpResponse(json.dumps(response, cls=DjangoJSONEncoder)) #return to ajax as success with all the new records.
            
        return super(MyView, self).get(request)


class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('listall')
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(BookDelete, self).dispatch(*args, **kwargs)
        
    def get_context_data(self, **kwargs):
        context = super(BookDelete, self).get_context_data(**kwargs)
        context['curruser'] = UserProfile.objects.get(user=self.request.user)
        return context


class BookCreate(CreateView):
    model = Book
    form_class = BookForm
    
class BookUpdate(UpdateView):
    model = Book
    form_class = BookForm
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(BookUpdate, self).dispatch(*args, **kwargs)
        
    def get_context_data(self, **kwargs):
        context = super(NoteUpdate, self).get_context_data(**kwargs)
        context['curruser'] = UserProfile.objects.get(user=self.request.user)
        return context


class BookDetail(DetailView):
    model = Book
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(BookDetail, self).dispatch(*args, **kwargs)
        
    def get_context_data(self, **kwargs):
        context = super(BookDetail, self).get_context_data(**kwargs)
        context['curruser'] = UserProfile.objects.get(user=self.request.user)
        return context



# Create your views here.
def bookstore_list(request, genre):
    if genre == "":
        all_books = Book.objects.all().order_by("genre__title")
        total = all_books.count()
    else:
        all_books = Book.objects.filter(genre__title__iexact=genre)
        total = all_books.count()
    return render(request, 'bookstore/index.html', {'bookstore': all_books, 'total': total})

def bookstore_author(request, author):
    pieces = author.split('/') #extract different tags separated by /
    # allnotes = Note.objects.none() #required when doing normal filter pipe query ... see below
    #for p in pieces:
        #This is to combine results from different querysets from SAME model using normal pipe
        #https://groups.google.com/forum/#!topic/django-users/0i6KjzeM8OI
        #If the querysets are from different models, have to use itertools
        #http://chriskief.com/2015/01/12/combine-2-django-querysets-from-different-models/
        #allnotes = allnotes | Note.objects.filter(tag__title__iexact=p) # can have duplicates ... need another method
        
    #http://stackoverflow.com/questions/852414/how-to-dynamically-compose-an-or-query-filter-in-django
    # Turn list of values into list of Q objects
    queries = [Q(pricerange__title__iexact=value) for value in pieces]
    # Take one Q object from the list
    query = queries.pop()
    # Or the Q object with the ones remaining in the list
    for item in queries:
        query |= item
    print(query)
    # Query the model
    all_books = Book.objects.filter(query).distinct().order_by('genre__title')
    total = all_books.count()
    return render(request, 'bookstore/index.html', {'pieces':pieces, 'bookstore': all_books, 'total': total})
    
def book(request, book_id):
    book = Book.objects.get(id=book_id) 
    return render(request, 'bookstore/book_detail.html', {'book':book})
    
    
class BookList(ListView):
    #https://docs.djangoproject.com/en/1.7/topics/class-based-views/generic-display/
    model = Book
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(BookList, self).dispatch(*args, **kwargs)

    
    def get_queryset(self):
                #self.request.user will contain the "User" object, however,
        #user field in the Note model is an instance of "UserProfile" object
        #So need to ensure that when we filter all the user owned notes, we
        #filter using the 'correct' UserProfile instance based on logged in "User" object 
        #in self.request.user
        curruser = UserProfile.objects.get(user=self.request.user)

        genre = self.kwargs['genre']
        if genre == '':
            #filter based on current logged in user
            self.queryset = Book.objects.filter(user=curruser)

            return Book.objects.all()
        else:
            #filter based on current logged in user

bookstore/templates/bookstore/base.html
{# Load the author library #}
{% load bootstrap3 %}

<head>
  <title>
    {%block title%}
    {%endblock%}
  </title>
</head>
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1%}

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script type="text/css">
.mynavbar {
    display:block;
    margin:0px;
    padding:0px;
    height:50px;
}

</script>

...
<body>
<div class="mynavbar">
        <ul class="nav nav-tabs navbar-right">
              <li role="presentation" class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="true">
                  {%if user.is_authenticated%}
                      <img src="/media/{{curruser.picture}}" height="30px" %} />
                      Hi {{user.username}}!
                  {%else%}
                      Login here!
                  {%endif%}
                  
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  {%if user.is_authenticated%}
                      <li><a href="/accounts/logout">Logout</a></li>
                      <li><a href="/add">Add a new book</a></li>
                      <li><a href="/list">View all my books</a></li>
                  {%else%}
                      <li><a href="/accounts/login">Login</a></li>
                  {%endif%}
                
                      
                </ul>
              </li>
            </ul>
</div>
<body>
{%block content%}
	To be replaced by actual content
{%endblock%}
</body>

bookstore/templates/bookstore/base1.html
{# Load the author library #}
{% load bootstrap3 %}

<head>
  <title>
    {%block title%}
    {%endblock%}
  </title>
</head>
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1%}
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.3/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.14.30/js/bootstrap-datetimepicker.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.14.30/css/bootstrap-datetimepicker.min.css">
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script type="text/javascript">
    $(document).ready(function() {
        jQuery.ajaxSettings.traditional = true; //Important 
        
        /*Important functions to enable CSRF token as Django requires it*/
        function getCookie(name) {
            var cookieValue = null;
            var i = 0;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (i; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var csrftoken = getCookie('csrftoken');
    
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        /*end CSRF token */
    
        /*Setting the format of the datepicker and datetimepicker*/
        $('.dateinput').datepicker({
            format: "yyyy/mm/dd"
        });
        $('.datetimeinput').datetimepicker({
            format: "YYYY-MM-DD HH:mm"
        });
    
       
        $('.creategenre').click(function(e) {
            formid = $(this).parent().attr("id"); //find the formid of the button pressed via parent 
            
            $.ajax({
                type: "POST",
                url: "/add/",
                dataType: "json",
                data: {
                    "title": $("#" + formid + " #id_title").val(),
                    "color": $("#" + formid + " #id_color").val(),
                    "fontcolor": $("#" + formid + " #id_fontcolor").val(),
                    "form": $("#" + formid).serialize(),
    
                },
                success: function(data) {
                    if (data.status == 1){
                        $('#mymessage').html("")
                        //Populate the dropdown list with all the folders returned in json
                        var $el = $("#id_folder");
                        $el.empty(); // remove old options
                        $el.append($("<option></option>").attr("value", "").text("---------"));
                        $.each(data.message, function(key, value) {
                            $el.append($("<option></option>").attr("value", value.id).text(value.title));
                        });
                    }
                    else{
                        $('#mymessage').html("<p>New folder creation error</p>"+data.message)
                    }
                    
                },
                crossDomain: false, // obviates need for sameOrigin test
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type)) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
        });
        
        $('.createauthor').click(function(e) {
            formid = $(this).parent().attr("id"); //find the formid of the button pressed via parent 
            
            $.ajax({
                type: "POST",
                url: "/add/",
                dataType: "json",
                data: {
                    "title": $("#" + formid + " #id_title").val(),
                    "color": $("#" + formid + " #id_color").val(),
                    "fontcolor": $("#" + formid + " #id_fontcolor").val(),
                    "form": $("#" + formid).serialize(),
    
                },
                success: function(data) {
                    if (data.status == 1){
                        $('#mymessage').html("")
                        //Populate the dropdown list with all the folders returned in json
                        var $el = $("#id_tag");
                        $el.empty(); // remove old options
                        $.each(data.message, function(key, value) {
                            $el.append($("<option></option>").attr("value", value.id).text(value.title));
                        });
                    }
                    else{
                        $('#mymessage').html("<p>New tag creation error</p>"+data.message)
                    }
                },
                crossDomain: false, // obviates need for sameOrigin test
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type)) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
        });
        
        $('.btn.addnote').click(function(e) {
            formid = $(this).parent().attr("id"); //find the formid of the button pressed via parent 
    
            $.ajax({
                type: "POST",
                url: "/add/",
                dataType: "json",
                data: {
                     "title": $("#" + formid + " #id_title").val(),
                     "done": $("#" + formid + " #id_done").prop("checked"),
                     "content": $("#" + formid + " #id_content").val(),
                     "due": $("#" + formid + " #id_due").val(),
                     "color": $("#" + formid + " #id_color").val(),
                     "fontcolor": $("#" + formid + " #id_fontcolor").val(),
                     "folder": $("#" + formid + " #id_folder").val(),
                     "tag": $("#" + formid + " #id_tag").val(),                
                     "form": $("#" + formid).serialize(),
    
                },
                success: function(data) {
                    $('#mymessage').html("")
                    if (data.status == 1){ //if there are no errors
                        
                        //http://stackoverflow.com/questions/503093/how-can-i-make-a-redirect-page-using-jquery
                        window.location.replace("/list") //to redirect to another page
                    }
                    else{
                        $('#mymessage').html(data.message)
                    }
                },
                crossDomain: false, // obviates need for sameOrigin test
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type)) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
        });
        
        /* To reset the modal input fields when modal is closed.*/
        $('#myModal').on('hidden.bs.modal', function(){
            $(this).find('form')[0].reset();
        });
        /* To reset the modal input fields when modal is closed.*/
        $('#myModal2').on('hidden.bs.modal', function(){
            $(this).find('form')[0].reset();
        });
    });
</script>
</head>
<body>
{%block content%}

{%endblock%}
</body>

bookstore/templates/bookstore/book.html
<!DOCTYPE html>
<html>
    <head>
        <title>{{book.title}}</title>
    </head>
    <body>
        Title:{{book.title}} <br/>
        Synopsis:{{book.synopsis}}<br/>
        Genre:{{book.genre}}<br/>
        Author(s):
        <ul>
        <!--https://docs.djangoproject.com/en/1.7/ref/templates/builtins/#for-->
        {%for t in book.author.all%}
            <li>{{t.author}}</li>
        {%endfor%}
        </ul>
    </body>
</html>

bookstore/templates/bookstore/book_confirm_delete.html
<form action="" method="post">{% csrf_token %}
    		<p>Are you sure you want to delete "{{ object }}"?</p>
    		<input type="submit" value="Confirm" />
</form>

bookstore/templates/bookstore/book_detail.html
{%extends 'bookstore/base.html'%}
{%block title%}
    Book - {{book.title}}
{%endblock%}
{%block content%}
    <div class="container">
        <h4>Title</h4> 
        <p>{{book.title}}</p>
        <h4>Synopsis</h4>
        <p>{{book.synopsis}}</p>
        <h4>Genre</h4>
        <p>{{book.genre}}</p>
        <h4>Author(s):</h4>
                <ul>
                <!--https://docs.djangoproject.com/en/1.7/ref/templates/builtins/#for-->
                {%for t in book.author.all%}
                    <li>{{t.title}}</li>
                {%endfor%}
                </ul>
    </div>
{%endblock%}

bookstore/templates/bookstore/book_form.html
{%extends 'bookstore/base.html'%}
{% load crispy_forms_tags %}
{%block content%}
<div class="container">
    <div class="row">
        <div class="col-md-6">
    <!--distinguish between update or create view-->
    <!--http://stackoverflow.com/questions/18806703/within-a-template-distinguish-between-create-and-update-form-->
    {%if object%}
        <h1>Update {{object.title}}</h1>
    {%else%}
        <h1>Add a New Book</h1>
    {%endif%}
    {% crispy form %}
	</div>
     </div>
</div>
{%endblock%}

bookstore/templates/bookstore/book_hybrid.html
{%extends 'bookstore/base.html'%}
{% load crispy_forms_tags %}
{%block content%}
<div id="mymessage" class="form-group alert-danger">
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>Add a new book</h3>
            {%if addbook_form %}
                {%crispy addbook_form%}
            {%endif%}
            
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Add New Genre</h4>
                  </div>
                  <div class="modal-body">
                    <!--MODAL ADD FOLDER-->
                    {%if addgenre_form%} {% crispy addgenre_form %} {%endif%}
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>
            
            <div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Add New Author</h4>
                  </div>
                  <div class="modal-body">
                    {%if addauthor_form%} {% crispy addauthor_form %} {%endif%}
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>

        </div>
    </div>
</div>
{%endblock%}

bookstore/templates/bookstore/book_list.html
{%load staticfiles%}
<link rel="stylesheet" type="text/css" href="{% static 'bookstore/style.css' %}" />
    <h2>Total number of books: {{total}}</h2>
    {% if object_list  %}
        {% for book in object_list  %}
            <a href={%url 'detail' book.id %}>
            	<div class="bdisplay" style="background:{{book.color}};color:{{book.fontcolor}}">
            	  <div id="base" style="border-color:{{book.folder.color}} transparent transparent transparent;">
  </div>
            <br>
            <u>{{book.title}}</u>
            <br>
            {{book.synopsis}}
      </div>
            </a>
        {% endfor %}
    {% else %}
        <p>No books are available.</p>
    {% endif %}

bookstore/templates/bookstore/index.html
{%load staticfiles%}
<link rel="stylesheet" type="text/css" href="{% static 'bookstore/style.css' %}" />

<h1 fontcolor='#ffffff'>Total number of books: {{total}}</h1>

{% if bookstore %}
    <ul>
    {% for book in bookstore %}
        <a href={%url 'detail' book.id %}>
            <div class="bdisplay" style="background:{{note.color}};color:{{note.fontcolor}}">
                <u class = 'boxtext'>{{book.title}}</u>
                <br>
                {{book.synopsis}}
            </div>
        </a>

    {% endfor %}
    </ul>
{% else %}
    <p>No books are available.</p>
{% endif %}